"""empty message

Revision ID: 25cdf9bc3d9a
Revises: f0de9bcbfc67
Create Date: 2021-11-23 16:03:42.563556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cdf9bc3d9a'
down_revision = 'f0de9bcbfc67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fir_joo', sa.String(length=6), server_default='980109', nullable=True))
        batch_op.add_column(sa.Column('sec_joo', sa.String(length=7), server_default='1157119', nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=50), server_default='01022369764', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('number')
        batch_op.drop_column('sec_joo')
        batch_op.drop_column('fir_joo')

    # ### end Alembic commands ###
