"""empty message

Revision ID: 494518737349
Revises: 673cd2a725f0
Create Date: 2021-10-07 17:45:55.992544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494518737349'
down_revision = '673cd2a725f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('fk_board_voter_board_id_board'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_board_voter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'board_id', name=op.f('pk_board_voter'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_voter')
    # ### end Alembic commands ###
