"""empty message

Revision ID: 6c0be4193a46
Revises: fbd025549b1a
Create Date: 2021-10-07 16:14:35.294275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0be4193a46'
down_revision = 'fbd025549b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hits', sa.Integer(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('hits')

    # ### end Alembic commands ###
