"""empty message

Revision ID: e1e1dc0c61dc
Revises: f708ad848182
Create Date: 2021-11-25 11:49:46.141650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1e1dc0c61dc'
down_revision = 'f708ad848182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tel', sa.String(length=50), nullable=False))
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.VARCHAR(length=50), server_default=sa.text("'01022369764'"), nullable=False))
        batch_op.drop_column('tel')

    # ### end Alembic commands ###
