"""empty message

Revision ID: f0de9bcbfc67
Revises: adaf957a51f5
Create Date: 2021-10-18 16:42:01.905922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0de9bcbfc67'
down_revision = 'adaf957a51f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('likes')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
