"""empty message

Revision ID: f708ad848182
Revises: 25cdf9bc3d9a
Create Date: 2021-11-23 16:04:34.874095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f708ad848182'
down_revision = '25cdf9bc3d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fir_joo',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text("'980109'"))
        batch_op.alter_column('sec_joo',
               existing_type=sa.VARCHAR(length=7),
               nullable=False,
               existing_server_default=sa.text("'1157119'"))
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'01022369764'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'01022369764'"))
        batch_op.alter_column('sec_joo',
               existing_type=sa.VARCHAR(length=7),
               nullable=True,
               existing_server_default=sa.text("'1157119'"))
        batch_op.alter_column('fir_joo',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text("'980109'"))

    # ### end Alembic commands ###
