"""empty message

Revision ID: fbd025549b1a
Revises: cb57e8a0265d
Create Date: 2021-10-07 14:14:58.453808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd025549b1a'
down_revision = 'cb57e8a0265d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_voter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_voter',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('answer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='fk_board_voter_answer_id_answer', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_board_voter_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'answer_id', name='pk_board_voter')
    )
    # ### end Alembic commands ###
